haeum/urls.py
from django.contrib import admin
from django.urls import include
from django.conf.urls.static import static
from haeum import settings
from django.conf.urls import url

urlpatterns = [
   url(r'^admin/', admin.site.urls),
    url(r'^', include('user.urls')),
    url(r'^post/', include('post.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from post.views import *

app_name = 'post'

urlpatterns = [
    url(r'^$', index, name='index'),
]

user/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from user.views import *

app_name = 'user'

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^mypage/$', mypage, name='mypage'),
    url(r'^thanks/$', thanks, name='thanks'),
    url(r'^calendar/$', calendar, name='calendar'),
    url(r'^heartfield/$', TemplateView.as_view(template_name='heart_field.html'), name='heartfield'),
]

post/models.py
from django.db import models
from datetime import datetime
import os, uuid

DISCLOSURE_CHOICES = (
    (0, 'private'),
    (1, 'public')
)

# Create your models here.
class Board(models.Model):
    title = models.CharField(max_length=30, verbose_name='제목')
    contents = models.TextField(verbose_name='내용')
    writer = models.ForeignKey('user.User', on_delete=models.CASCADE,
                               verbose_name='글쓴이')
    disclosure = models.SmallIntegerField(choices=DISCLOSURE_CHOICES)
    hits = models.IntegerField(default=0, verbose_name='조회수')
    registered_dttm = models.DateTimeField(auto_now_add=True,
                                           verbose_name='등록시간')
    def __str__(self):
        return self.title

    class Meta:
        db_table = 'haeum board'
        verbose_name = '게시판'
        verbose_name_plural = '게시판'

class Post_thanks(models.Model):
    contents = models.TextField(verbose_name='내용')
    image_url = models.CharField(max_length=30, verbose_name='이미지url')
    writer = models.ForeignKey('post.board', on_delete=models.CASCADE,
                               verbose_name='게시글')
    class Meta:
        db_table = 'haeum thanks'
        verbose_name = '감사열매'
        verbose_name_plural = '감사열매'

def image_upload_to(instance, filename):
    ext = filename.split('.')[-1]
    return os.path.join(instance.UPLOAD_PATH, "%s.%s" % (uuid.uuid4(), ext))
    #16자리 고유한 아이디 생성

class Photo(models.Model):
    UPLOAD_PATH = 'user-upload'
    title = models.CharField(max_length=30, verbose_name='제목')
    image = models.ImageField(upload_to=image_upload_to)
    order = models.SmallIntegerField() # image numbering
    reg_date = models.DateTimeField(verbose_name='날짜', default=datetime.now())

    class Meta:
        db_table = 'haeum photo'
        verbose_name = '사진'
        verbose_name_plural = '사진'
        ordering = ['order']

class Board_thanks(models.Model):
    title = models.CharField(max_length=30, verbose_name='제목')
    contents = models.TextField(verbose_name='내용')
    writer = models.ForeignKey('user.User', on_delete=models.CASCADE,
                               verbose_name='글쓴이')
    registered_dttm = models.DateTimeField(auto_now_add=True,
                                           verbose_name='등록시간')
    def __str__(self):
        return self.title

    class Meta:
        db_table = 'thanks board'
        verbose_name = '감사노트'
        verbose_name_plural = '감사노트'

user/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    email = models.EmailField(verbose_name='이메일')
    name = models.CharField(max_length=20, verbose_name='이름')
    password = models.CharField(max_length=128, verbose_name='비밀번호')

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'haeum user'
        verbose_name = '셀원'
        verbose_name_plural = '셀원'

post/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'index.html', { 'email': request.session.get('user') })

user/views.py
from django.shortcuts import render, redirect, reverse

from user.models import User
from post.models import Photo
# Create your views here.

def index(request):
    user_list = User.objects.all()
    user = User.objects.filter(email=request.session.get('user'))
    photo_lists = Photo.objects.all()
    photo_list = []
    if len(photo_lists)>5:
        for p in photo_lists:
            photo_list.append(p)
            if len(photo_list)>=5:
                    break
    elif len(photo_lists)>0:
        for p in photo_lists:
            photo_list.append(p)

    res_data = {
        'user_list' : user_list,
        'photo_list' : photo_list     
        }
    if user:
        res_data['user'] = user[0]
    return render(request, 'index.html', res_data)

def login(request):
    error_msg = {}
    if request.method=="POST":
        user_id = request.POST.get('email')
        user_pw = request.POST.get('password')
        if user_id and user_pw:
            user = User.objects.filter(email=user_id)
            if user:
                if user[0].password == user_pw:
                    request.session['user'] = user_id
                    return redirect(reverse('user:index'))
                else:
                    error_msg['error'] = "아이디나 비밀번호가 잘못되었습니다."
            else:
                error_msg['error'] = "아이디나 비밀번호가 잘못되었습니다."
    return render(request, 'login.html', error_msg)

def logout(request):
    if 'user' in request.session:
        del(request.session['user'])

    return redirect(reverse('user:index'))

def mypage(request):
    user = User.objects.filter(email=request.session.get('user'))
    res_data = {"user" : user}
    if request.method=="POST":
        pass
    return render(request, 'mypage.html', res_data)

def calendar(request):
    user = User.objects.filter(email=request.session.get('user'))
    res_data = {}
    if user:
        res_data['user'] = user[0]
    return render(request, 'calendar_ex5.html', res_data)

def thanks(request):
    user = User.objects.filter(email=request.session.get('user'))
    res_data = {}
    if user:
        res_data['user'] = user[0]
    return render(request, 'thanks_note.html', res_data)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Ogani Template">
    <meta name="keywords" content="Ogani, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- favicon.ico 404 (Not Found) -->
    <link rel="icon" href="data:;base64,iVBORw0KGgo=">
    <title>하음셀 | 슬기로운 하음생활</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;900&display=swap" rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
    <script src="https://code.jquery.com/jquery-1.9.1.min.js"></script>
    {% block header %}
    {% endblock %}

</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Humberger Begin -->
    <div class="humberger__menu__overlay"></div>
    <div class="humberger__menu__wrapper">
        <div class="humberger__menu__logo">
            <a href="{% url 'user:index' %}"><img src="{% static 'img/logo_rabit.png' %}" alt=""></a>
        </div>
        <div class="humberger__menu__widget">
            <div class="header__top__right__auth">
                <a href="{% url 'user:login' %}"><i class="fa fa-user"></i> Login</a>
            </div>
        </div>
        <nav class="humberger__menu__nav mobile-menu">
            <ul>
                <li class="active"><a href="{% url 'user:index' %}">Home</a></li>
                <li><a href="{% url 'user:heartfield' %}">마음밭</a></li>
                <li><a href="{% url 'user:calendar' %}">사진첩</a></li>
                <li><a href="./blog.html">감사일기</a></li>
                <li><a href="#">Pages</a>
                    <ul class="header__menu__dropdown">
                        <li><a href="./shop-details.html">Shop Details</a></li>
                        <li><a href="./shoping-cart.html">Shoping Cart</a></li>
                        <li><a href="./checkout.html">Check Out</a></li>
                        <li><a href="./blog-details.html">Blog Details</a></li>
                    </ul>
                </li>       
            </ul>
        </nav>
        <div id="mobile-menu-wrap"></div>
        <div class="header__top__right__social">
            <a href="#"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-linkedin"></i></a>
            <a href="#"><i class="fa fa-pinterest-p"></i></a>
        </div>
        <div class="humberger__menu__contact">
            <ul>
                <li><i class="fa fa-envelope"></i> sohn0356@naver.com</li>
                <li>문제 발견시 연락주세요~</li>
            </ul>
        </div>
    </div>
    <!-- Humberger End -->

    <!-- Header Section Begin -->
    <header class="header">
        <div class="header__top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-md-6">
                        <div class="header__top__left">
                            <ul>
                                <li><i class="fa fa-envelope"></i>{{ user.name }} ♥</li>
                                <li>하음셀</li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <div class="header__top__right">
                            <div class="header__top__right__social">
                                <a href="#"><i class="fa fa-facebook"></i></a>
                                <a href="#"><i class="fa fa-instagram"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                            </div>
                            {% if request.session.user %}
                                <div class="header__top__right__auth">
                                    <a href="{% url 'user:mypage' %}"><i class="fa fa-user"></i> MyPage </a>
                                </div>
                                <div class="header__top__right__auth">
                                    <a href="{% url 'user:logout' %}"> <i class="fa fa-sign-out"></i>logout</a>
                                </div>
                            {% else %}
                                <div class="header__top__right__auth">
                                    <a href="{% url 'user:login' %}"><i class="fa fa-user"></i> Login</a>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="header__logo">
                        <a href="{% url 'user:index' %}"><img src="{% static 'img/logo_rabit.png' %}" alt=""></a>
                    </div>
                </div>
                <div class="col-lg-6">
                    <nav class="header__menu">
                        <ul>
                            <li class="active"><a href="{% url 'user:index' %}">Home</a></li>
                            <li><a href="{% url 'user:heartfield' %}">마음밭</a></li>
                            <li><a href="{% url 'user:calendar' %}">사진첩</a></li>
                            <li><a href="{% url 'user:thanks' %}">감사일기</a></li>
                            <li><a href="#">Pages</a>
                                <ul class="header__menu__dropdown">
                                    <li><a href="./shop-details.html">Shop Details</a></li>
                                    <li><a href="./shoping-cart.html">Shoping Cart</a></li>
                                    <li><a href="./checkout.html">Check Out</a></li>
                                    <li><a href="./blog-details.html">Blog Details</a></li>
                                </ul>
                            </li>                            
                        </ul>
                    </nav>
                </div>
                <div class="col-lg-3">    
                    <!-- <div class="header__cart"> 알림 기능으로 활용 가능!!!
                        <ul>
                            <li><a href="#"><i class="fa fa-heart"></i> <span>1</span></a></li>
                            <li><a href="#"><i class="fa fa-shopping-bag"></i> <span>3</span></a></li>
                        </ul>
                        <div class="header__cart__price">item: <span>$150.00</span></div>
                    </div> -->
                </div>
            </div>
            <div class="humberger__open">
                <i class="fa fa-bars"></i>
            </div>
        </div>
    </header>
    <!-- Header Section End -->

    {% block contents %}
    {% endblock %}

    <!-- Footer Section Begin -->
    <footer class="footer spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="footer__about">
                        <div class="footer__about__logo">
                            <a href="{% url 'user:index' %}"><img src="{% static 'img/logo_rabit.png' %}" alt=""></a>
                        </div>
                        <ul>
                            <li>Phone: 010.5141.4281</li>
                            <li>Email: sohn0356@naver.com</li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-6 offset-lg-1">
                    <div class="footer__widget">
                        <h6>Useful Links</h6>
                        <ul>
                            <li><a href="#">교회링크</a></li>
                            <li><a href="#">교회 인스타</a></li>
                        </ul>
                        <ul>
                            <li><a href="#">교회 유튜브 링크</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-12">
                    <div class="footer__widget">
                        <h6>Join Our Newsletter Now</h6>
                        <p>Get E-mail updates about our latest shop and special offers.</p>
                        <form action="#">
                            <input type="text" placeholder="Enter your mail">
                            <button type="submit" class="site-btn">Subscribe</button>
                        </form>
                        <div class="footer__widget__social">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-instagram"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="footer__copyright">
                        <div class="footer__copyright__text"><p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p></div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer Section End -->

    <!-- Js Plugins -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.min.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.js' %}"></script>
    <script src="{% static 'js/mixitup.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

    {% block footer %}
    {% endblock %}


</body>

</html>

templates/calendar_ex3.html
{% load static %}

<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" id="bootstrap-css">
<script src="https://code.jquery.com/jquery-1.9.1.min.js"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

<!------ Include the above in your HEAD tag ---------->

<!DOCTYPE html>
<html>
<head>



<link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i" rel="stylesheet">

<script>

	$(document).ready(function() {
	    var date = new Date();
		var d = date.getDate();
		var m = date.getMonth();
		var y = date.getFullYear();
		
		/*  className colors
		
		className: default(transparent), important(red), chill(pink), success(green), info(blue)
		
		*/		
		
		  
		/* initialize the external events
		-----------------------------------------------------------------*/
	
		$('#external-events div.external-event').each(function() {
		
			// create an Event Object (http://arshaw.com/fullcalendar/docs/event_data/Event_Object/)
			// it doesn't need to have a start or end
			var eventObject = {
				title: $.trim($(this).text()) // use the element's text as the event title
			};
			
			// store the Event Object in the DOM element so we can get to it later
			$(this).data('eventObject', eventObject);
			
			// make the event draggable using jQuery UI
			$(this).draggable({
				zIndex: 999,
				revert: true,      // will cause the event to go back to its
				revertDuration: 0  //  original position after the drag
			});
			
		});
	
	
		/* initialize the calendar
		-----------------------------------------------------------------*/
		
		var calendar =  $('#calendar').fullCalendar({
			header: {
				left: 'title',
				center: 'agendaDay,agendaWeek,month',
				right: 'prev,next today'
			},
			editable: true,
			firstDay: 1, //  1(Monday) this can be changed to 0(Sunday) for the USA system
			selectable: true,
			defaultView: 'month',
			
			axisFormat: 'h:mm',
			columnFormat: {
                month: 'ddd',    // Mon
                week: 'ddd d', // Mon 7
                day: 'dddd M/d',  // Monday 9/7
                agendaDay: 'dddd d'
            },
            titleFormat: {
                month: 'MMMM yyyy', // September 2009
                week: "MMMM yyyy", // September 2009
                day: 'MMMM yyyy'                  // Tuesday, Sep 8, 2009
            },
			allDaySlot: false,
			selectHelper: true,
			select: function(start, end, allDay) {
				var title = prompt('Event Title:');
				if (title) {
					calendar.fullCalendar('renderEvent',
						{
							title: title,
							start: start,
							end: end,
							allDay: allDay
						},
						true // make the event "stick"
					);
				}
				calendar.fullCalendar('unselect');
			},
			droppable: true, // this allows things to be dropped onto the calendar !!!
			drop: function(date, allDay) { // this function is called when something is dropped
			
				// retrieve the dropped element's stored Event Object
				var originalEventObject = $(this).data('eventObject');
				
				// we need to copy it, so that multiple events don't have a reference to the same object
				var copiedEventObject = $.extend({}, originalEventObject);
				
				// assign it the date that was reported
				copiedEventObject.start = date;
				copiedEventObject.allDay = allDay;
				
				// render the event on the calendar
				// the last `true` argument determines if the event "sticks" (http://arshaw.com/fullcalendar/docs/event_rendering/renderEvent/)
				$('#calendar').fullCalendar('renderEvent', copiedEventObject, true);
				
				// is the "remove after drop" checkbox checked?
				if ($('#drop-remove').is(':checked')) {
					// if so, remove the element from the "Draggable Events" list
					$(this).remove();
				}
				
			},
			
			events: [
				{
					title: 'All Day Event',
					start: new Date(y, m, 1)
				},
				{
					id: 999,
					title: 'Repeating Event',
					start: new Date(y, m, d-3, 16, 0),
					allDay: false,
					className: 'info'
				},
				{
					id: 999,
					title: 'Repeating Event',
					start: new Date(y, m, d+4, 16, 0),
					allDay: false,
					className: 'info'
				},
				{
					title: 'Meeting',
					start: new Date(y, m, d, 10, 30),
					allDay: false,
					className: 'important'
				},
				{
					title: 'Lunch',
					start: new Date(y, m, d, 12, 0),
					end: new Date(y, m, d, 14, 0),
					allDay: false,
					className: 'important'
				},
				{
					title: 'Birthday Party',
					start: new Date(y, m, d+1, 19, 0),
					end: new Date(y, m, d+1, 22, 30),
					allDay: false,
				},
				{
					title: 'Click for Google',
					start: new Date(y, m, 28),
					end: new Date(y, m, 29),
					url: 'https://ccp.cloudaccess.net/aff.php?aff=5188',
					className: 'success'
				}
			],			
		});
		
		
	});

</script>
<style>

	body {
	    margin-bottom: 40px;
		margin-top: 40px;
		text-align: center;
		font-size: 14px;
		font-family: 'Roboto', sans-serif;
		background:url(http://www.digiphotohub.com/wp-content/uploads/2015/09/bigstock-Abstract-Blurred-Background-Of-92820527.jpg);
		}
		
	#wrap {
		width: 1100px;
		margin: 0 auto;
		}
		
	#external-events {
		float: left;
		width: 150px;
		padding: 0 10px;
		text-align: left;
		}
		
	#external-events h4 {
		font-size: 16px;
		margin-top: 0;
		padding-top: 1em;
		}
		
	.external-event { /* try to mimick the look of a real event */
		margin: 10px 0;
		padding: 2px 4px;
		background: #3366CC;
		color: #fff;
		font-size: .85em;
		cursor: pointer;
		}
		
	#external-events p {
		margin: 1.5em 0;
		font-size: 11px;
		color: #666;
		}
		
	#external-events p input {
		margin: 0;
		vertical-align: middle;
		}

	#calendar {
/* 		float: right; */
        margin: 0 auto;
		width: 900px;
		background-color: #FFFFFF;
		  border-radius: 6px;
        box-shadow: 0 1px 2px #C3C3C3;
		-webkit-box-shadow: 0px 0px 21px 2px rgba(0,0,0,0.18);
-moz-box-shadow: 0px 0px 21px 2px rgba(0,0,0,0.18);
box-shadow: 0px 0px 21px 2px rgba(0,0,0,0.18);
		}

</style>
</head>
<body>
<div id='wrap'>

<div id='calendar'></div>

<div style='clear:both'></div>
</div>
</body>
</html>

templates/calendar_ex4.html
{% extends "base.html" %}

{% load static %}
{% block header %}

<link href="{% static 'assets/css/fullcalendar.css' %}" rel='stylesheet' />
<link href="{% static 'assets/css/fullcalendar.print.css' %}" rel='stylesheet' media='print' />
<link href="{% static 'assets/css/calendar.css' %}" rel='stylesheet' />

{% endblock %}
{% block contents %}
<section class="hero" id="section_calendar">
    <div class="container">
        <div class="row">
            <div class="col-lg-2"></div>
            <div class="col-lg-8">
                <div id='calendar'></div>
            </div>
            <div class="col-lg-2"></div>
        </div>
        <div class="row">
            <div class="col-lg-2"></div>
            <div class="col-lg-8">
                <img src="{% static 'img/bg.png' %}">
            </div>
            <div class="col-lg-2"></div>
        </div>
</section>
{% endblock %}

{% block footer %}
    <script src="{% static 'assets/js/jquery-1.10.2.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/js/jquery-ui.custom.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/js/fullcalendar.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/js/calendar.js' %}" type="text/javascript"></script>
{% endblock %}

templates/calendar_ex6.html
{% load static %}

<section class="hero" id="section_calendar">
    <div class="container">
        <div class="row">
            <div class="col-lg-2"></div>
            <div class="col-lg-8">
                <div id='calendar'></div>
            </div>
            <div class="col-lg-2"></div>
        </div>
        <div class="row">
            <div class="col-lg-2"></div>
            <div class="col-lg-8">
                <img src="{% static 'img/bg.png' %}">
            </div>
            <div class="col-lg-2"></div>
        </div>
</section>

templates/login.html
{% extends "base.html" %}

{% block header %}

<script>
    $(document).ready(function(){
        var error = '{{ error }}';
        if (error){
            alert(error);
        }        
    });
</script>
{% endblock %}

{% block contents %}
    <!-- Checkout Section Begin -->
    <section class="checkout spad">
        <div class="container">
            <div class="checkout__form">
                <h4>Welcome to the 하음셀</h4>
                <form method="POST">
                    {% csrf_token %}
                    <br/><br/>
                    <div class="row">
                        <div class="col-lg-3 com-md-3"></div>
                        <div class="col-lg-6 col-md-6">
                            <div class="checkout__order">
                                <h4>로그인</h4>
                                    <div class="col-lg-12">
                                        <div class="checkout__input">
                                            <p>아이디<span>*</span></p>
                                            <input type="email" name="email">
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="checkout__input">
                                            <p>패스워드<span>*</span></p>
                                            <input type="password" name="password">
                                        </div>
                                    </div>
                                <button type="submit" class="site-btn">로그인</button>
                            </div>
                        </div>
                        <div class="col-lg-3 com-md-3"></div>
                    </div>
                </form>
            </div>
        </div>
    </section>
    <!-- Checkout Section End -->
 
{% endblock %}

templates/main.html
<a href="https://colorlib.com/wp/templates/"><img src="https://colorlib.com/wp/wp-content/uploads/sites/2/colorlib-push-logo.png" alt="Colorlib logo"></a>
<h1 style="text-align:center;">Thank you for using our template!</h1>
<p style="text-align:center;">For more awesome templates please visit <strong><a href="https://colorlib.com/wp/templates/">Colorlib</a></strong>.</p>
<br>
<p style="text-align:center; color:red;"><strong>Copyright information for the template can't be altered/removed unless you purchase a license.</strong>

<p style="text-align:center;"><strong>Removing copyright information without the license will result in suspension of your hosting and/or domain name(s).</strong>

<p style="text-align:center;"><strong>More information about the license is available <a href="https://colorlib.com/wp/licence/">here</a></strong>.</p>

<style>
img {
  margin: 0 auto;
  display: block;
  margin-top: 20%;
}
</style>

templates/mypage.html
{% extends "base.html" %}

{% block header %}
<script src="https://code.jquery.com/jquery-1.9.1.min.js"></script>
<script>
    $(document).ready(function(){
        var error = '{{ error }}';
        if (error){
            alert(error);
        }        
    });
</script>
{% endblock %}

{% block contents %}
    <!-- Checkout Section Begin -->
    <section class="checkout spad">
        <div class="container">
            <div class="checkout__form">
                <h4>Mypage</h4>
                <form method="POST">
                    {% csrf_token %}
                    <br/><br/>
                    <div class="row">
                        <div class="col-lg-3 com-md-3"></div>
                        <div class="col-lg-6 col-md-6">
                            <div class="checkout__order">
                                <h4>Profile</h4>
                                    <div class="row">
                                        <div class="col-lg-5">
                                            <div class="checkout__input">
                                                <p>name<span>*</span></p>
                                                <input type="text" name="name" value="{{ user.0.name }}">
                                            </div>
                                        </div>
                                        <div class="col-lg-1"></div>
                                        <div class="col-lg-5">
                                            <div class="checkout__input">
                                                <p>email<span>*</span></p>
                                                <input type="email" name="email" value="{{ user.0.email }}">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-lg-5">
                                            <div class="checkout__input">
                                                <p>password</p>
                                                <input type="password" name="password">
                                            </div>
                                        </div>
                                        <div class="col-lg-1"></div>
                                        <div class="col-lg-5">
                                            <div class="checkout__input">
                                                <p>re-password</p>
                                                <input type="password" name="re-password">
                                            </div>
                                        </div>
                                    </div>
                                    
                                <button type="submit" class="site-btn">수정하기</button>
                            </div>
                        </div>
                        <div class="col-lg-3 com-md-3"></div>
                    </div>
                </form>
            </div>
        </div>
    </section>
    <!-- Checkout Section End -->
 
{% endblock %}

    

    